# Generated by Django 4.1.2 on 2022-10-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_tasks',
            field=models.ManyToManyField(to='core.task'),
        ),
    ]
