# Generated by Django 4.1.1 on 2022-09-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_therapist',
            field=models.BooleanField(default=False),
        ),
    ]
