# Generated by Django 4.1.2 on 2022-10-12 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_assigned_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
