# Generated by Django 4.1.1 on 2022-09-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_choice_question_task_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='questions',
        ),
        migrations.AddField(
            model_name='task',
            name='questions',
            field=models.ManyToManyField(to='core.question'),
        ),
    ]
