# Generated by Django 4.1.1 on 2022-09-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_task_questions_task_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='left_choice',
        ),
        migrations.RemoveField(
            model_name='question',
            name='right_choice',
        ),
        migrations.AddField(
            model_name='question',
            name='left_choice',
            field=models.ManyToManyField(related_name='left_choice', to='core.choice'),
        ),
        migrations.AddField(
            model_name='question',
            name='right_choice',
            field=models.ManyToManyField(related_name='right_choice', to='core.choice'),
        ),
    ]
