# Generated by Django 4.1.2 on 2022-10-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='therapist_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
