# Generated by Django 4.1.2 on 2022-10-23 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_therapist_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_therapist', to=settings.AUTH_USER_MODEL),
        ),
    ]
