# Generated by Django 4.1.1 on 2022-09-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_question_test_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='test_text',
            new_name='heading',
        ),
    ]
