# Generated by Django 4.1.1 on 2022-09-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_test_text_question_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='side',
            new_name='left_side',
        ),
    ]
