# Generated by Django 4.1.2 on 2022-10-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigment_active',
            field=models.BooleanField(default=False),
        ),
    ]
