# Generated by Django 4.1.1 on 2022-09-27 14:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_side_choice_left_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=core.models.recipe_image_file_path)),
            ],
        ),
    ]
