# Generated by Django 4.1.1 on 2022-09-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_basicchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='left_choice',
        ),
        migrations.RemoveField(
            model_name='question',
            name='right_choice',
        ),
        migrations.AddField(
            model_name='question',
            name='Choices',
            field=models.ManyToManyField(to='core.basicchoice'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
