# Generated by Django 4.1.1 on 2022-09-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_question_left_choice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Choices',
            new_name='choices',
        ),
    ]
