# Generated by Django 4.1.1 on 2022-09-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_choices_question_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicchoice',
            name='assigned_to',
            field=models.ManyToManyField(to='core.task'),
        ),
    ]
