# Generated by Django 4.1.1 on 2022-10-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_basicchoice_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicchoice',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, to='core.task'),
        ),
    ]
