# Generated by Django 4.1.2 on 2022-10-25 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_customchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_questions', to='core.task')),
                ('choices', models.ManyToManyField(to='core.customchoice')),
            ],
        ),
    ]
