# Generated by Django 4.1.2 on 2022-10-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_customquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customquestion',
            name='heading',
        ),
    ]
