# Generated by Django 4.1.1 on 2022-10-08 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_tag_basicchoice_tags_task_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='text',
            new_name='name',
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
