# Generated by Django 4.1.2 on 2022-10-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_user_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='assigment_active',
            new_name='assignment_active',
        ),
    ]
