# Generated by Django 4.1.2 on 2022-10-31 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_assigment_active_user_assignment_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicchoice',
            old_name='text',
            new_name='data1',
        ),
        migrations.RenameField(
            model_name='basicchoice',
            old_name='image',
            new_name='data2',
        ),
        migrations.RenameField(
            model_name='customchoice',
            old_name='image',
            new_name='data1',
        ),
        migrations.RenameField(
            model_name='customchoice',
            old_name='text',
            new_name='data2',
        ),
    ]
