# Generated by Django 4.1.2 on 2022-11-03 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_text_basicchoice_data1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data1', models.CharField(max_length=255)),
                ('data2', models.CharField(max_length=255)),
                ('data3', models.CharField(max_length=255)),
                ('data4', models.CharField(max_length=255)),
                ('data5', models.CharField(max_length=255)),
                ('assigned_to', models.ManyToManyField(blank=True, to='core.task')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='core.tag')),
            ],
        ),
        migrations.CreateModel(
            name='FourQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourchoice_questions', to='core.task')),
                ('choices', models.ManyToManyField(to='core.fourchoice')),
            ],
        ),
    ]
