# Generated by Django 4.1.2 on 2022-11-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_fourchoice_fourquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_image_text',
            field=models.BooleanField(default=True),
        ),
    ]
