# Generated by Django 4.1.2 on 2022-11-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_task_is_image_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_image_text',
        ),
    ]
