# Generated by Django 4.1.2 on 2022-11-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_task_is_image_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('HARD', 'Hard')], default='EASY', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('FOUR CHOICES', 'Four Choices'), ('CONNECT PAIRS', 'Connect Pairs')], default='CONNECT PAIRS', max_length=20),
        ),
    ]
