# Generated by Django 4.1.2 on 2022-11-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_task_difficulty_alter_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Four Choices (Image-Texts)', 'Four Choices Image'), ('Four Choices (Text-Image)', 'Four Choices Text'), ('Connect Pairs (Text-Image)', 'Connect Pairs Text Image'), ('Connect Pairs (Image-Text)', 'Connect Pairs Text Text')], max_length=50),
        ),
    ]
