# Generated by Django 4.1.2 on 2022-11-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Hard', 'Hard')], max_length=20),
        ),
    ]
