# Generated by Django 4.1.2 on 2022-11-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_task_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fourchoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='fourchoice',
            name='tags',
        ),
    ]
