# Generated by Django 4.1.2 on 2022-11-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_fourchoice_assigned_to_fourchoice_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customchoice',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='customchoice',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.task'),
        ),
    ]
