# Generated by Django 4.1.2 on 2022-11-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Four_Choices_Image-Texts', 'Four Choices Image'), ('Four_Choices_Text-Images', 'Four Choices Text'), ('Connect_Pairs_Text-Image', 'Connect Pairs Text Image'), ('Connect_Pairs_Text-Text', 'Connect Pairs Text Text')], max_length=50),
        ),
    ]
