# Generated by Django 4.1.2 on 2022-11-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_answerfourchoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerfourchoice',
            old_name='data1',
            new_name='correct_option',
        ),
        migrations.RenameField(
            model_name='answerfourchoice',
            old_name='data2',
            new_name='incorrect_option1',
        ),
        migrations.RenameField(
            model_name='answerfourchoice',
            old_name='data3',
            new_name='incorrect_option2',
        ),
        migrations.RenameField(
            model_name='answerfourchoice',
            old_name='data4',
            new_name='incorrect_option3',
        ),
        migrations.RenameField(
            model_name='answerfourchoice',
            old_name='data5',
            new_name='question_data',
        ),
        migrations.RenameField(
            model_name='fourchoice',
            old_name='data1',
            new_name='correct_option',
        ),
        migrations.RenameField(
            model_name='fourchoice',
            old_name='data2',
            new_name='incorrect_option1',
        ),
        migrations.RenameField(
            model_name='fourchoice',
            old_name='data3',
            new_name='incorrect_option2',
        ),
        migrations.RenameField(
            model_name='fourchoice',
            old_name='data4',
            new_name='incorrect_option3',
        ),
        migrations.RenameField(
            model_name='fourchoice',
            old_name='data5',
            new_name='question_data',
        ),
    ]
