# Generated by Django 4.1.3 on 2022-11-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_taskresult_date_created_user_day_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskresult',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
