# Generated by Django 4.1.3 on 2022-12-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_user_diagnosis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
